default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: high_priority
      processes: 3
    - queues: low_priority
      processes: 1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
